### ISSUE TITLE
When set to "", some config options use the default value instead

### ISSUE THREAD

**Issue by bbusse** [albertito/chasquid#25] opened 2022-01-13 22:24 UTC
The 'drop_characters' config option defaults to 'drop_characters: "."' but when left empty (drop_characters: "") still drops the '.'

**Comment by albertito** [comment] 2022-01-14 00:53
Thanks for reporting this! I just edited the title since this bug can be generalized to many of the config options.

## Description

When a configuration option is set to `""`, chasquid will use the default value instead of the empty string.

In particular, the `drop_characters` and `suffix_separators` options are both affected.

## Workaround

Until a fix is implemented, instead of using `""`, use any value that isn't found in the user part of addresses, like `"🐞"`.

**Comment by albertito** [comment] 2022-01-14 15:10
Commit 1741ff536be6cdbd378f2d9f91fc406a2b22f9e6 should fix this problem, and @bbusse kindly confirmed it works for them (thanks!).

It's currently in `next`, and as usual I will let it sit there for a bit in case something comes up before moving it to `master`, but it will definitely be included in the next release.

**Comment by albertito** [comment] 2022-03-08 10:03
The fix is included in the v1.9 release.

Thanks again for reporting this!

**Closed by albertito** 2022-03-08 10:03 UTC
Labels: bug
